# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('photo', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('ambassador_lead', models.CharField(max_length=30)),
            ],
        ),
    ]
